Changed infracost event

diff --git a/.github/workflows/infracost.yml b/.github/workflows/infracost.yml
--- a/.github/workflows/infracost.yml
+++ b/.github/workflows/infracost.yml
@@ -2,26 +2,49 @@ name: Check Cost Changes with Infracost
 
 on:
   pull_request:
-    branches:
-      - master
+    branches: [ master ]
+    # types: [opened, synchronize]
 
 jobs:
   infracost:
     runs-on: ubuntu-latest
+
     steps:
-      - name: Checkout repository
-        uses: actions/checkout@v2
-        
-      - name: Install Infracost
-        run: |
-          curl -fsSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh
-          infracost --version  # Verifica la instalación de Infracost
-        
-      - name: Run Infracost
-        run: infracost --git --show-skipped --format json > infracost.json
-        
-      - name: Comment on GitHub PR
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          PR_NUMBER: ${{ github.event.number }}
-        run: infracost comment github --path=infracost.json --repo=$GITHUB_REPOSITORY --pull-request=$PR_NUMBER --github-token=$GITHUB_TOKEN --behavior=update
+    - name: Checkout code
+      uses: actions/checkout@v2
+      path: 02/terraform
+
+    - name: Install infracost
+      run: curl -fsSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh
+
+    - name: Run infracost diff
+      id: infracost
+      run: |
+        cd 02/terraform
+        infracost --git --format json > infracost.json || echo "Infracost failed"
+
+    - name: Check for changes in costs
+      run: |
+        changes=$(cat 02/terraform/infracost.json)
+        if [ -n "$changes" ]; then
+          echo "::set-output name=cost_changes::true"
+        else
+          echo "::set-output name=cost_changes::false"
+        fi
+
+    - name: Comment on Pull Request if there are cost changes
+      if: steps.infracost.outputs.cost_changes == 'true'
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      run: |
+        PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
+        cd 02/terraform
+        infracost comment github --path=infracost.json \
+          --repo=$GITHUB_REPOSITORY \
+          --pull-request=$PR_NUMBER \
+          --github-token=$GITHUB_TOKEN \
+          --behavior=update
+
+    - name: Fail if there are cost changes
+      if: steps.infracost.outputs.cost_changes == 'true'
+      run: exit 1
